### PR TITLE
modules/sasl, modules/route_replies: interpret messages even if they have prefix tags (resolves #1212)

### LINKED ISSUE #1212: SASL AUTHENTICATE does not work with a prefix
When an `AUTHENTICATE` message is sent from the server and it includes a prefix, it does not seem to be parsed as a proper SASL message. This causes a hang when trying to authenticate with our server ([mammon](https://github.com/mammon-ircd/mammon)).

RFC1459 specifies that prefixes are an optional part of messages, and the `SASL` specification does not prohibit prefixes on this specific message.

I believe this is related to how the `AUTHENTICATE`/etc messages are parsed [here](https://github.com/znc/znc/blob/79e979e5cdbcca8d969d1df7f8f370d56e9bdb00/modules/sasl.cpp#L215), but I'm not a ZNC dev.

Here's an example log taken with `znc -D`:
```
[2015-12-21 18:35:39.322267] (dan/testnet) IRC -> ZNC [:mammon.dnt CAP dan ACK :sasl ]
[2015-12-21 18:35:39.322502] (dan/testnet) ZNC -> IRC [AUTHENTICATE PLAIN] (queued)
[2015-12-21 18:35:40.325589] (dan/testnet) ZNC -> IRC [CAP REQ :server-time]
[2015-12-21 18:35:40.327845] (dan/testnet) IRC -> ZNC [:mammon.dnt CAP dan ACK :server-time ]
[2015-12-21 18:35:41.331506] (dan/testnet) ZNC -> IRC [AUTHENTICATE PLAIN]
[2015-12-21 18:35:41.333488] (dan/testnet) IRC -> ZNC [@time=2015-12-21T08:35:40.000Z :mammon.dnt AUTHENTICATE +]
[2015-12-21 18:35:41.333844] (dan/testnet) ZNC -> CLI [:mammon.dnt AUTHENTICATE +]
[2015-12-21 18:36:27.275089] (dan/testnet) CLI -> ZNC [PING localhost]
[2015-12-21 18:36:27.275283] (dan/testnet) ZNC -> CLI [:irc.znc.in PONG irc.znc.in localhost]
[2015-12-21 18:36:27.275404] (dan/testnet) ZNC -> IRC [PING localhost]
[2015-12-21 18:36:27.277628] (dan/testnet) IRC -> ZNC [@time=2015-12-21T08:36:26.000Z :mammon.dnt PONG localhost]
```

And here's me continuing the registration manually with `CAP END` to the `raw` module:
```
[2015-12-21 18:38:00.230835] (dan/testnet) CLI -> ZNC [PRIVMSG *raw :CAP END]
[2015-12-21 18:38:00.230954] (dan/testnet) ZNC -> CLI [:*raw!znc@znc.in PRIVMSG dan :YOU -> [PRIVMSG *raw :CAP END]]
[2015-12-21 18:38:00.231177] (dan/testnet) ZNC -> IRC [CAP END]
[2015-12-21 18:38:00.300740] (dan/testnet) IRC -> ZNC [@time=2015-12-21T08:37:59.000Z :mammon.dnt NOTICE dan :*** You are connected using TLSv1/SSLv3-ECDHE-RSA-AES256-GCM-SHA384-256]
[2015-12-21 18:38:00.300867] (dan/testnet) ZNC -> CLI [:*raw!znc@znc.in PRIVMSG dan :IRC -> [@time=2015-12-21T08:37:59.000Z :mammon.dnt NOTICE dan :*** You are connected using TLSv1/SSLv3-ECDHE-RSA-AES256-GCM-SHA384-256]]
[2015-12-21 18:38:00.301112] (dan/testnet) ZNC -> CLI [:mammon.dnt NOTICE dan :*** You are connected using TLSv1/SSLv3-ECDHE-RSA-AES256-GCM-SHA384-256]
[2015-12-21 18:38:00.301185] (dan/testnet) IRC -> ZNC [@time=2015-12-21T08:37:59.000Z :mammon.dnt 906 dan :SASL authentication aborted]
[2015-12-21 18:38:00.301234] (dan/testnet) ZNC -> CLI [:*raw!znc@znc.in PRIVMSG dan :IRC -> [@time=2015-12-21T08:37:59.000Z :mammon.dnt 906 dan :SASL authentication aborted]]
[2015-12-21 18:38:00.301398] (dan/testnet) ZNC -> CLI [:mammon.dnt 906 dan :SASL authentication aborted]
[2015-12-21 18:38:00.301461] (dan/testnet) IRC -> ZNC [@time=2015-12-21T08:37:59.000Z :mammon.dnt 001 dan :Welcome to the DanNet IRC Network, dan!~d@localhost.localdomain]
```

Please note that we also send prefixes with all of our numerics (and we can also send tags with numerics and `AUTHENTICATE` if they are enabled, as with `server-time` there). I'm not sure how that's handled by/with the `sasl` module.

OS version: Fedora 23 - Linux twi 4.2.6-300.fc23.x86_64 #1 SMP Tue Nov 10 19:32:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
ZNC version: 16a8c77

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29297229-sasl-authenticate-does-not-work-with-a-prefix?utm_campaign=plugin&utm_content=tracker%2F1759&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1759&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nasonfish**
This alters the `sasl` and `route_replies` module to use the hook `OnRawMessage` or `OnNumericMessage` instead of `OnRaw`, to ensure the module catches any messages from the server that it intends to catch, regardless of tags applied before the actual command/numeric.

`OnRaw` delivers to the plugin raw lines directly from the IRC server, whose tokens can be unpredictable depending on if the server has `server-time` enabled or if the IRC server prefixes `AUTHENTICATE` or the numeric with the server name, etc. - checking if the first parameter of a raw message is "AUTHENTICATE" was unpredictable for our use, as it would only work if the server doesn't prefix the message with either of these tags. (We could only interpret the raw line `AUTHENTICATE +`, not `@time=2015-12-21T18:11:52.000Z :irc.znc.in AUTHENTICATE +`, for example).

`OnRawMessage` and `OnNumericMessage`, however, interprets the raw message first, stripping out `server-time` prefixes and finding the command and its arguments, without any ambiguity. So, using this instead, we can find the actual command the IRC server is sending us and any arguments, and interpret it correctly without assuming there's no prefixes.

So, this resolves issue #1212, where mammon was sending ZNC prefixed `AUTHENTICATE` messages and this module was not interpreting them correctly, and corrects behavior with route_replies not routing messages correctly and giving "timeout" errors erroneously when the numerics it was expecting were sent correctly.

### CODE REVIEW

File: modules/sasl.cpp [hunk 1]
```diff
@@ -212,17 +212,17 @@ class CSASLMod : public CModule {
         }
     }
 
-    EModRet OnRaw(CString& sLine) override {
-        if (sLine.Token(0).Equals("AUTHENTICATE")) {
-            Authenticate(sLine.Token(1, true));
-        } else if (sLine.Token(1).Equals("903")) {
+    EModRet OnRawMessage(CMessage& sMessage) override {
+        if (sMessage.GetCommand().AsUpper().Equals("AUTHENTICATE")) {
```
Comment (DarthGandalf) [inline modules/sasl.cpp]: .Equals() does case-insensitive comparison.

File: modules/sasl.cpp [hunk 2]
```diff
@@ -212,17 +212,17 @@ class CSASLMod : public CModule {
...
+            Authenticate(sMessage.GetParam(0));
+        } else if (sMessage.GetCommand().Equals("903")) {
```
Comment (DarthGandalf) [inline modules/sasl.cpp]: There is a separate hook for that, OnNumericMessage.
It wasn't available in non-CMessage variant...

**Comment by nasonfish** [comment]
Thanks, I'll make those changes and update this PR.

**Comment by nasonfish** [comment]
Okay, this pull request has been expanded to resolve issues with`route_replies`, the redundant `.AsUpper(` usage has been removed, and usage of the more specific `onNumericMessage(` in the SASL module has been added.

File: modules/sasl.cpp (hunk 1 above)
Comment (kaniini) [inline modules/sasl.cpp]: IRC commands should be considered case-insensitive.

File: modules/route_replies.cpp [hunk 3]
```diff
@@ -258,8 +258,8 @@ class CRouteRepliesMod : public CModule {
         SendRequest();
     }
 
-    EModRet OnRaw(CString& sLine) override {
-        CString sCmd = sLine.Token(1).AsUpper();
+    EModRet OnRawMessage(CMessage& sMessage) override {
```
Comment (DarthGandalf) [inline modules/route_replies.cpp]: `s` is for strings

Comment (DarthGandalf) [inline modules/route_replies.cpp]: I think, `msg` would be fine

**Comment by nasonfish** [comment]
Alright, I've changed the variable name from `sMessage` to `msg`, as it is of type `CMessage` which is not a string - thanks again, @DarthGandalf.
